/* Generated by scripts/build-config.js from .env - do not edit by hand. */
window.ZANDF_CONFIG = {
  "emailjs": {
    "publicKey": "fbuOgEHLQGag4oAZf",
    "serviceId": "zandf",
    "templateId": "template_0j2vnfh"
  },
  "cloudinary": {
    "cloudName": "kdvfz52j",
    "uploadPreset": "zandf-files"
  },
  "firebase": {
    "apiKey": "AIzaSyCusOWbdgfnP3oF_4DcXkyT3ea_KXoVQg0",
    "authDomain": "zandf-19287.firebaseapp.com",
    "projectId": "zandf-19287",
    "storageBucket": "zandf-19287.firebasestorage.app",
    "messagingSenderId": "700621051696",
    "appId": "1:700621051696:web:58f1c17dd42116fb865af5",
    "measurementId": "G-J3LS0NSD7S",
    "adminEmail": "zandf211@gmail.com"
  }
};
