/* ============================================
   ZANDF — Firebase init
   Reads window.ZANDF_CONFIG.firebase (generated by
   scripts/build-config.js from .env) and initializes
   the Firebase app. Exposes a small facade on
   window.ZANDF_FIREBASE for the rest of the site.

   Must be loaded AFTER js/config.js and AFTER
   the Firebase compat SDK scripts.
   ============================================ */

window.ZANDF_FIREBASE = (function () {
  const cfg =
    (typeof window.ZANDF_CONFIG !== 'undefined' && window.ZANDF_CONFIG.firebase) || {};

  if (typeof firebase === 'undefined' || !cfg.projectId || !cfg.apiKey) {
    console.warn('ZANDF: Firebase SDK missing or not configured.');
    return null;
  }

  const app = firebase.initializeApp({
    apiKey: cfg.apiKey,
    authDomain: cfg.authDomain,
    projectId: cfg.projectId,
    storageBucket: cfg.storageBucket,
    messagingSenderId: cfg.messagingSenderId,
    appId: cfg.appId,
    measurementId: cfg.measurementId
  });

  const auth = firebase.auth(app);
  const db = firebase.firestore(app);
  const FieldValue = firebase.firestore.FieldValue;

  let analytics = null;
  try {
    analytics = firebase.analytics(app);
  } catch (e) {
    // Analytics is optional — ignore if it fails (e.g. blocked or disabled).
  }

  return {
    app,
    auth,
    db,
    analytics,
    FieldValue,
    adminEmail: cfg.adminEmail || ''
  };
})();
