/* ============================================
   ZANDF — Build script
   Reads .env and generates js/config.js
   (the browser-consumable, public-only config).

   Usage:  node scripts/build-config.js

   Only PUBLIC values are written to config.js.
   Secrets (e.g. EMAILJS_PRIVATE_KEY) stay in .env
   and are never committed or exposed to the browser.
   ============================================ */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'js', 'config.js');

function parseEnv(src) {
  const out = {};
  for (const line of src.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const m = trimmed.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/i);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return out;
}

function build() {
  if (!fs.existsSync(ENV_PATH)) {
    console.error('Missing .env — copy env.example to .env first, then run this script.');
    process.exit(1);
  }

  const env = parseEnv(fs.readFileSync(ENV_PATH, 'utf8'));

  const config = {
    emailjs: {
      publicKey: env.EMAILJS_PUBLIC_KEY || '',
      serviceId: env.EMAILJS_SERVICE_ID || '',
      templateId: env.EMAILJS_TEMPLATE_ID || ''
    },
    cloudinary: {
      cloudName: env.CLOUDINARY_CLOUD_NAME || '',
      uploadPreset: env.CLOUDINARY_UPLOAD_PRESET || ''
    },
    firebase: {
      apiKey: env.FIREBASE_API_KEY || '',
      authDomain: env.FIREBASE_AUTH_DOMAIN || '',
      projectId: env.FIREBASE_PROJECT_ID || '',
      storageBucket: env.FIREBASE_STORAGE_BUCKET || '',
      messagingSenderId: env.FIREBASE_MESSAGING_SENDER_ID || '',
      appId: env.FIREBASE_APP_ID || '',
      measurementId: env.FIREBASE_MEASUREMENT_ID || '',
      adminEmail: env.FIREBASE_ADMIN_EMAIL || ''
    }
  };

  const body = [
    '/* Generated by scripts/build-config.js from .env - do not edit by hand. */',
    'window.ZANDF_CONFIG = ' + JSON.stringify(config, null, 2) + ';',
    ''
  ].join('\n');

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, body, 'utf8');
  console.log('Wrote ' + path.relative(ROOT, OUT_PATH));
}

build();
